### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by lucaslop** [UnBArqDsw2020-2/2020.2_G4-Meubrecho-frontend#2]
## Descrição

Deverá construir a página de login se baseando no protótipo.

## Tarefas

- [x] Deverá conter um campo do tipo input para email
- [x] Deverá conter um campo do tipo input para senha
- [x] Devera conter um botão para fazer login

## Critérios adicionais

- [x] Um usuário só poderá se logar se estiver previamente  cadastrado
- [x] Um usuário só poderá se logar se os dados estiverem corretos
- [x] Em caso de algum erro de dados ou não cadastrado, mostrar ao usuário

## Informação adicional

** adaptações do protótipos são aceitas**

**Comment by VictorLeviPeixoto** [comment]
Fechada com o PR #13
