### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by lucaslop** [UnBArqDsw2020-2/2020.2_G4-Meubrecho-frontend#3]
## Descrição

Deverá construir a página de registro se baseando no protótipo.

## Tarefas
- [ ] Deverá conter um capo do tipo input para nome
- [ ] Deverá conter um campo do tipo input para email
- [ ] Deverá conter um campo do tipo input para senha
- [ ] Deverá conter um campo do tipo input para CPF
- [ ] Deverá conter um campo do tipo input para número de telefone
- [ ] Devera conter um botão para fazer registro

## Critérios adicionais

- [ ] Um usuário só poderá se registrar se o email não tiver sido  cadastrado por outro usuário
- [ ] Um usuário só poderá se registrar se o cpf for válido
- [ ] Em caso de algum erro dos dados, mostrar ao usuário

## Informação adicional

**Se caso julgar necessário, poderá realizar alterçaões/adaptações em relação ao prototípo**

**Comment by VictorLeviPeixoto** [comment]
Fechada com o PR #13
