### ISSUE TITLE
Criar um novo produto

### ISSUE THREAD

**Issue by lucaslop** [UnBArqDsw2020-2/2020.2_G4-Meubrecho-frontend#6]
## Descrição

na tela **cadastro de novo produto** deverá conter todos os itens para cadastro de um produto

## Tarefas

- [x] Deverá conter campo para o registro de fotos do produto
- [x] Deverá conter campo do tipo input para o nome do produto
- [x] Deverá conter campo do tipo input para a descrição do produto
- [x] Deverá conter campo do tipo input para o valor do produto
- [x] Deverá conter campo do tipo dropdown para as tags

## Critérios adicionais

- [x] O valor do produto não pode ser negativo
- [x] O valor do produto pode ser zero
- [x] O produto deve ser relacionado com o usuário que o criou

## Informação adicional

**Se caso julgar necessário, poderá realizar alterçaões/adaptações em relação ao prototípo**

**Comment by VictorLeviPeixoto** [comment]
Fechada com o PR #26
