### ISSUE TITLE
Retirar um produto da loja

### ISSUE THREAD

**Issue by lucaslop** [UnBArqDsw2020-2/2020.2_G4-Meubrecho-frontend#7]
## Descrição

na tela **produto ofertados** , conterá os produtos anunciados que o **vendedor** cadastrou. Somente ele poderá retirar do catálago da loja

## Tarefas

- [x] Somente o **vendendor** poderá deletar o **seu** produto anunciado
- [x] Nesse tela conterá todos os produtos **usuário** que foi anunciado
- [x] Deverá conter um botão para exlcuir o produto

## Informação adicional

**Se caso julgar necessário, poderá realizar alterçaões/adaptações em relação ao prototípo**

**Comment by VictorLeviPeixoto** [comment]
Fechada com o PR #27
