### ISSUE TITLE
Filtrar um produto

### ISSUE THREAD

**Issue by lucaslop** [UnBArqDsw2020-2/2020.2_G4-Meubrecho-frontend#8]
## Descrição

Na tela home, deverá ser possivel filtrar um produto pelo nome do produto

## Tarefas

- [x] Criar um filtro na tela home para filtrar um produto pelo nome

## Critérios adicionais

- [x] O filtro deve retornar resultados de uma pesquisa aberta
- [x] O filtro deve conter filtros (baseado nas tags) para a pesquisa

## Informação adicional

**Se caso julgar necessário, poderá realizar alterçaões/adaptações em relação ao prototípo**

**Comment by VictorLeviPeixoto** [comment]
Finalizada com o PR #27
